version: '3.8'

services:
  candidate-db:
    container_name: candidate-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
      - candidate-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - candidate-network
  candidate-service:
    build: .
    container_name: candidate-service
    ports:
      - "3000:3000"
    depends_on:
      - candidate-db
    networks:
      - candidate-network

volumes:
  candidate-data:
    name: candidate-data

networks:
  candidate-network:
    # external: true